# Generated by Django 5.1.15 on 2026-04-12 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tricks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trick',
            name='demo_gif_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
